# Generated by Django 2.2 on 2018-09-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180926_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichapessoal',
            old_name='profesor',
            new_name='professor',
        ),
    ]
