# Generated by Django 2.2 on 2018-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180928_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank='true', upload_to='user/perfil', verbose_name='Foto Perfil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='frase',
            field=models.TextField(blank=True, max_length=200, verbose_name='Frase'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uf',
            field=models.CharField(blank=True, max_length=10, verbose_name='Estado'),
        ),
    ]
