# Generated by Django 2.2 on 2018-09-30 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180929_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField(verbose_name='Data de inicio da ficha')),
                ('data_end', models.DateField(verbose_name='Data de termino da ficha')),
                ('altura', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso')),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Torax')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peitoral')),
                ('axilar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Axilar')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cintura')),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quadril')),
                ('braco_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço esquerdo')),
                ('braco_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Braço direito')),
                ('antebraco_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço esquerdo')),
                ('antebraco_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço direito')),
                ('coxa_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa esquerda')),
                ('coxa_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa eireita')),
                ('panturilha_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pantirrilha esquerda')),
                ('panturilha_dir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pantirrilha direita')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_ficha', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Pessoal',
                'verbose_name_plural': 'Fichas Pessoais',
            },
        ),
        migrations.DeleteModel(
            name='FichaPessoal',
        ),
    ]
