# Generated by Django 2.2 on 2018-10-02 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181001_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='data',
        ),
        migrations.AddField(
            model_name='treino',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Inicio'),
            preserve_default=False,
        ),
    ]
