# Generated by Django 2.2 on 2018-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181001_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='data_fim',
            field=models.DateField(blank=True, verbose_name='Data Fim'),
        ),
    ]
