# Generated by Django 2.2 on 2018-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181003_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank='true', default='/user/perfil/avatar.png', upload_to='user/perfil', verbose_name='Foto Perfil'),
        ),
    ]
